dist: trusty
language: node_js
node_js:
- "10"

install:
- npm install

script:
- npm run lint
- npm run build
- npm run test
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run doc;
    npm run copy:example;
  fi

deploy:
- provider: npm
  skip_cleanup: true
  email: uxteam@adidas-group.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+
- provider: pages
  skip-cleanup: true
  local-dir: ./example
  github-token: $GITHUB_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+
